version: '3'

services:
  postgres_db:
    container_name: "postgres_db_mockdatabaseproject"
    image: postgres:16.1
    restart: "no"
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - /Users/aresende/Projects/mock-database/postgres:/var/lib/postgresql/data_1
      - ./my_pg_hba.conf:/var/lib/postgresql/data_1/pg_hba.conf
    
  mongo_db:
    container_name: "mongo_db_mockdatabaseproject"
    image: mongo
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - /Users/aresende/Projects/mock-database/mongodb:/data/db



volumes:
  postgres_db: {}
  mongo_db: {}